ClientMaster/Models/Client.cs
namespace ClientMaster.Models;

public class Client
{
    public int ClientID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime DateOfBirth { get; set; }
    public string StreetAddressLine1 { get; set; }
    public string? StreetAddressLine2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
    public int? ReferringClientID { get; set; }
    public virtual Client ReferringClient { get; set; }
    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
    public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
}

ClientMaster/Pages/AddClient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ClientMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ClientMaster.Pages;

[BindProperties]
public class AddClientModel : PageModel
{

    private readonly ClientBaseContext ClientBaseContext;
    public AddClientModel(ClientBaseContext CBC)
    {
        ClientBaseContext = CBC;
    }

    public string Message;
    public string MessageColor;

    public SelectList StateSelectList;
    public SelectList ReferrerSelectList;
    public Client Client { get; set; }

    public string AddNumber { get; set; }
    public string AddEmail { get; set; }

    public void OnGet()
    {
        MessageColor = "Green";
        Message = "Please enter the required information and click Add Client.";

        var states = new List<string>
        {
            "Alabama", "Alaska", "Arizona", "Arkansas", "California",
            "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
            "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
            "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
            "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
            "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
            "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
            "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
            "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
            "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
        };

        StateSelectList = new SelectList(states);

        // Load Referrer SelectList with all clients
        var ClientList = ClientBaseContext.Clients.Select(c => new { c.ClientID, Name = c.FirstName + " " + c.LastName }).ToList();
        ReferrerSelectList = new SelectList(ClientList, "ClientID", "Name");
    }

    public async Task<IActionResult> OnPostAddClientAsync()
    {
        try
        {
            // Add client to Client table
            ClientBaseContext.Clients.Add(Client);
            await ClientBaseContext.SaveChangesAsync();

            // If entered, add phone number or email to respective database table
            if (AddNumber != null)
            {
                PhoneNumber number = new PhoneNumber { ClientID = Client.ClientID, Number = AddNumber };
                ClientBaseContext.PhoneNumbers.Add(number);
            }

            if (AddEmail != null)
            {
                EmailAddress email = new EmailAddress { ClientID = Client.ClientID, Email = AddEmail };
                ClientBaseContext.EmailAddresses.Add(email);
            }

            await ClientBaseContext.SaveChangesAsync();

            TempData["strMessageColor"] = "Green";
            TempData["strMessage"] = Client.FirstName + " " + Client.LastName + " was successfully added.";
        }
        catch (DbUpdateException dbUpdateException)
        {
            TempData["strMessageColor"] = "Red";
            TempData["strMessage"] = Client.FirstName + " " + Client.LastName + " was NOT added: " + dbUpdateException.InnerException.Message;
        }
        return Redirect("Clients");
    }
}

ClientMaster/Pages/Clients.cshtml.cs
using ClientMaster.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ClientMaster.Pages;

public class ClientsModel : PageModel
{

    private readonly ClientBaseContext ClientBaseContext;
    public ClientsModel(ClientBaseContext CBC)
    {
        ClientBaseContext = CBC;
    }

    public string Message;
    public string MessageColor;

    public IList<Client> ClientIList;

    public async Task OnGetAsync()
    {
        if (TempData["strMessage"] == null)
        {
            TempData["strMessage"] = "Select a client.";
            TempData["strMessageColor"] = "Green";
        }
        else
        {
            Message = TempData["strMessage"].ToString();
            MessageColor = TempData["strMessageColor"].ToString();
        }

        // Get all clients from Client table
        ClientIList = await ClientBaseContext.Clients.ToListAsync();
    }
}

ClientMaster/Pages/DeleteClient.cshtml.cs
using ClientMaster.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace ClientMaster.Pages;

[BindProperties]
public class DeleteClientModel : PageModel
{
    private readonly ClientBaseContext ClientBaseContext;
    public DeleteClientModel(ClientBaseContext CBC)
    {
        ClientBaseContext = CBC;
    }

    public string Message;
    public string MessageColor;

    public SelectList StateSelectList;
    public SelectList ReferrerSelectList;
    public Client Client { get; set; }

    public async Task<IActionResult> OnGetAsync(int ClientID)
    {
        MessageColor = "Green";
        Message = "Edit any information and click Update Client.";

        // Get selected client via ClientID
        Client = await ClientBaseContext.Clients.FindAsync(ClientID);

        if (Client != null)
        {
            return Page();
        }
        else
        {
            TempData["strMessage"] = "Client not found.";
            TempData["strMessageColor"] = "Red";

            return Redirect("Clients");
        }
    }

    public async Task<IActionResult> OnPostDeleteClientAsync(string firstName, string lastName)
    {
        try
        {
            // Remove Client from table
            ClientBaseContext.Clients.Remove(Client);
            await ClientBaseContext.SaveChangesAsync();

            TempData["strMessageColor"] = "Green";
            TempData["strMessage"] = firstName + " " + lastName + " was successfully removed.";
        }
        catch (DbUpdateException dbUpdateException)
        {
            SqlException dbSqlException = dbUpdateException.InnerException as SqlException;
            // Unique error message if Client is set as referrer of another Client
            if (dbSqlException.Number == 547)
            {
                TempData["strMessageColor"] = "Red";
                TempData["strMessage"] = firstName + " " + lastName + " was NOT removed because it refers another client.";
            }
            else
            {
                TempData["strMessageColor"] = "Red";
                TempData["strMessage"] = firstName + " " + lastName + " was NOT removed: " + dbUpdateException.InnerException.Message;
            }
        }
        return Redirect("Clients");
    }
}

ClientMaster/Pages/EditClient.cshtml.cs
using ClientMaster.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ClientMaster.Pages;

[BindProperties]
public class EditClientModel : PageModel
{
    private readonly ClientBaseContext ClientBaseContext;
    public EditClientModel(ClientBaseContext CBC)
    {
        ClientBaseContext = CBC;
    }

    public string Message;
    public string MessageColor;

    public SelectList StateSelectList;
    public SelectList ReferrerSelectList;
    public Client Client { get; set; }

    public string AddNumber { get; set; }
    public string AddEmail { get; set; }

    public async Task<IActionResult> OnGetAsync(int ClientID)
    {
        MessageColor = "Green";
        Message = "Edit any information and click Update Client.";

        Client = await ClientBaseContext.Clients.FindAsync(ClientID);

        if (Client != null)
        {
            // Load other properties related to Client from database
            await ClientBaseContext.Entry(Client)
                .Reference(c => c.ReferringClient)
                .LoadAsync();

            await ClientBaseContext.Entry(Client)
                .Collection(c => c.PhoneNumbers)
                .LoadAsync();

            await ClientBaseContext.Entry(Client)
                .Collection(c => c.EmailAddresses)
                .LoadAsync();

            var states = new List<string>
            {
                "Alabama", "Alaska", "Arizona", "Arkansas", "California",
                "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
                "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
                "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
                "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
                "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
                "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
                "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
                "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
                "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
            };

            StateSelectList = new SelectList(states);

            // Load SelectList with all clients except current ClientID
            var ClientList = ClientBaseContext.Clients
                .Where(c => c.ClientID != Client.ClientID)
                .Select(c => new { c.ClientID, Name = c.FirstName + " " + c.LastName }).ToList();
            ReferrerSelectList = new SelectList(ClientList, "ClientID", "Name");

            return Page();
        }
        else
        {
            TempData["strMessage"] = "Client not found.";
            TempData["strMessageColor"] = "Red";

            return Redirect("Clients");
        }
    }

    public async Task<IActionResult> OnPostUpdateClientAsync()
    {
        // Get list of checkmarked phone numbers and email addresses
        var selectedNumbers = Request.Form["selectedNumbers"].ToList();
        var selectedEmails = Request.Form["selectedEmails"].ToList();

        try
        {
            // Remove each select phone number
            foreach (var id in selectedNumbers)
            {
                PhoneNumber number = ClientBaseContext.PhoneNumbers.Find(Int32.Parse(id));
                if (number != null)
                {
                    ClientBaseContext.PhoneNumbers.Remove(number);
                }
            }

            // Remove each selected email address
            foreach (var id in selectedEmails)
            {
                EmailAddress email = ClientBaseContext.EmailAddresses.Find(Int32.Parse(id));
                if (email != null)
                {
                    ClientBaseContext.EmailAddresses.Remove(email);
                }

            }

            // If entered, add phone number or email to respective database table
            if (AddNumber != null)
            {
                PhoneNumber number = new PhoneNumber { ClientID = Client.ClientID, Number = AddNumber };
                ClientBaseContext.PhoneNumbers.Add(number);
            }

            if (AddEmail != null)
            {
                EmailAddress email = new EmailAddress { ClientID = Client.ClientID, Email = AddEmail };
                ClientBaseContext.EmailAddresses.Add(email);
            }

            // Update the existing entry of Client in the table
            ClientBaseContext.Clients.Update(Client);
            await ClientBaseContext.SaveChangesAsync();

            TempData["strMessageColor"] = "Green";
            TempData["strMessage"] = Client.FirstName + " " + Client.LastName + " was successfully updated.";
        }
        catch (DbUpdateException dbUpdateException)
        {
            TempData["strMessageColor"] = "Red";
            TempData["strMessage"] = Client.FirstName + " " + Client.LastName + " was NOT updated: " + dbUpdateException.InnerException.Message;
        }
        return Redirect("Clients");
    }

}

ClientMaster/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ClientMaster.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ClientMaster/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClientMaster.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

ClientMaster/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClientMaster.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ClientMaster/Pages/ViewClient.cshtml.cs
using ClientMaster.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ClientMaster.Pages;

[BindProperties]
public class ViewClientModel : PageModel
{
    private readonly ClientBaseContext ClientBaseContext;
    public ViewClientModel(ClientBaseContext CBC)
    {
        ClientBaseContext = CBC;
    }

    public string Message;
    public string MessageColor;

    public Client Client { get; set; }

    public async Task<IActionResult> OnGetAsync(int ClientID)
    {
        MessageColor = "Green";
        Message = "";

        Client = await ClientBaseContext.Clients.FindAsync(ClientID);

        if (Client != null)
        {
            // Load other properties related to Client from database
            await ClientBaseContext.Entry(Client)
                .Reference(c => c.ReferringClient)
                .LoadAsync();

            await ClientBaseContext.Entry(Client)
                .Collection(c => c.PhoneNumbers)
                .LoadAsync();

            await ClientBaseContext.Entry(Client)
                .Collection(c => c.EmailAddresses)
                .LoadAsync();

            return Page();
        }
        else
        {
            TempData["strMessage"] = "Client not found.";
            TempData["strMessageColor"] = "Red";

            return Redirect("Clients");
        }
    }
}

ClientMaster/Pages/AddClient.cshtml
@page
@model ClientMaster.Pages.AddClientModel
@{
    ViewData["Title"] = "Add Client";
}

<h1>Add Client</h1>
<label class="pt-1 pb-3" style="color: @Model.MessageColor">@Model.Message</label>

<div class="container">
    <form method="post">
        <div class="row p-1">
            <div class="col-4 w-auto">
                <label asp-for="Client.FirstName">First Name</label>
                <input asp-for="Client.FirstName" />
            </div>
            <div class="col-4 w-auto">
                <label asp-for="Client.LastName">Last Name</label>
                <input asp-for="Client.LastName" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-4">
                <label asp-for="Client.DateOfBirth">Date of Birth</label>
                <input asp-for="Client.DateOfBirth" type="date" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-8">
                <label asp-for="Client.StreetAddressLine1">Street Address Line 1</label>
                <input asp-for="Client.StreetAddressLine1" class="w-50" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-8">
                <label asp-for="Client.StreetAddressLine2">Street Address Line 2</label>
                <input asp-for="Client.StreetAddressLine2" class="w-50" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-3 w-auto">
                <label asp-for="Client.City">City</label>
                <input asp-for="Client.City" />
            </div>
            <div class="col-3 w-auto">
                <label asp-for="Client.State">State</label>
                <select asp-for="Client.State" asp-items="@Model.StateSelectList">
                    <option value=""></option>
                </select>
            </div>
            <div class="col-2 w-auto">
                <label asp-for="Client.Zip">Zip</label>
                <input asp-for="Client.Zip" maxlength="5" size="5" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="3"><label>Phone Numbers</label></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>New</td>
                            <td><input asp-for="AddNumber" /></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="3"><label>Email Addresses</label></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>New</td>
                            <td><input asp-for="AddEmail" /></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row p-3 ps-0">
            <div class="col-3 w-auto">
                <label asp-for="Client.ReferringClientID">Referring Client</label>
                <select asp-for="Client.ReferringClientID" asp-items="@Model.ReferrerSelectList">
                    <option value=""></option>
                </select>
            </div>
        </div>
        <div class="row p-3">
            <div class="col-3 w-auto">
                <a asp-page="Clients">Cancel</a>
            </div>
            <div class="col-3 w-auto">
                <input value="Add Client" type="submit" class="btn btn-primary" asp-page-handler="AddClient" />
            </div>
        </div>
    </form>
</div>

ClientMaster/Pages/Clients.cshtml
@page
@model ClientMaster.Pages.ClientsModel
@{
    ViewData["Title"] = "Clients";
}

<div class="text-center">
    <h1>Clients</h1>
    <label class="pt-1 pb-3" style="color: @Model.MessageColor">@Model.Message</label>


    <table class="table">
        <thead>
            <tr>
                <th><label>First Name</label></th>
                <th><label>Last Name</label></th>
                <th><label>Date of Birth</label></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in Model.ClientIList)
            {
                <tr>
                    <td><label>@client.FirstName</label></td>
                    <td><label>@client.LastName</label></td>
                    <td><label>@client.DateOfBirth.ToShortDateString()</label></td>
                    <td>
                        <a asp-page="/DeleteClient" asp-route-ClientID="@client.ClientID"><img src="~/images/trash.svg"></img></a>
                        <a asp-page="/EditClient" asp-route-ClientID="@client.ClientID"><img src="~/images/pencil-square.svg"></img></a>
                        <a asp-page="/ViewClient" asp-route-ClientID="@client.ClientID"><img src="~/images/arrow-right-square.svg"></img></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-page="/AddClient" class="btn btn-primary">Add New Client</a>

</div>

ClientMaster/Pages/DeleteClient.cshtml
@page
@model ClientMaster.Pages.DeleteClientModel
@{
    ViewData["Title"] = "Delete Client";
}

<div class="text-center">
    <h1 class="p-3">Delete Client</h1>
    <div class="container border border-dark w-50 p-3">
        <p>Are you sure you want to delete this client?</p>
        <p>@Model.Client.FirstName @Model.Client.LastName</p>
        <p>DOB: @Model.Client.DateOfBirth.ToShortDateString()</p>
        <form method="post">
            <input asp-for="Client.ClientID" type="hidden" />
            <input type="hidden" name="firstName" value="@Model.Client.FirstName" />
            <input type="hidden" name="lastName" value="@Model.Client.LastName" />
            <a asp-page="Clients" class="w-auto ps-3 pe-3">No</a>
            <button class="btn btn-danger w-auto ps-3 pe-3" type="submit" asp-page-handler="DeleteClient">Yes</button>
        </form>
    </div>
</div>

ClientMaster/Pages/EditClient.cshtml
@page
@model ClientMaster.Pages.EditClientModel
@{
    ViewData["Title"] = "Edit Client";
}

<h1>Edit Client</h1>
<label class="pt-1 pb-3" style="color: @Model.MessageColor">@Model.Message</label>

<div class="container">
    <form method="post">
        <input asp-for="Client.ClientID" type="hidden" />

        <div class="row p-1">
            <div class="col-4 w-auto">
                <label asp-for="Client.FirstName">First Name</label>
                <input asp-for="Client.FirstName" />
            </div>
            <div class="col-4 w-auto">
                <label asp-for="Client.LastName">Last Name</label>
                <input asp-for="Client.LastName" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-4">
                <label asp-for="Client.DateOfBirth">Date of Birth</label>
                <input asp-for="Client.DateOfBirth" type="date" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-8">
                <label asp-for="Client.StreetAddressLine1">Street Address Line 1</label>
                <input asp-for="Client.StreetAddressLine1" class="w-50" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-8">
                <label asp-for="Client.StreetAddressLine2">Street Address Line 2</label>
                <input asp-for="Client.StreetAddressLine2" class="w-50" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-3 w-auto">
                <label asp-for="Client.City">City</label>
                <input asp-for="Client.City" />
            </div>
            <div class="col-3 w-auto">
                <label asp-for ="Client.State">State</label>
                <select asp-for="Client.State" asp-items="@Model.StateSelectList">
                </select>
            </div>
            <div class="col-2 w-auto">
                <label asp-for="Client.Zip">Zip</label>
                <input asp-for="Client.Zip" maxlength="5" size="5" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2"><label>Phone Numbers</label></th>
                            <th><label>Delete?</label></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Client.PhoneNumbers != null && Model.Client.PhoneNumbers.Any())
                        {
                            int phoneIndex = 1;

                            @foreach (var number in Model.Client.PhoneNumbers)
                            {
                                <tr>
                                    <td>@phoneIndex</td>
                                    <td><label>@number.Number</label></td>
                                    <td><input type="checkbox" name="selectedNumbers" value="@number.PhoneNumberID" /></td>
                                </tr>
                                phoneIndex++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="3">No phone numbers available</td>
                            </tr>
                        }
                        <tr>
                            <td>New</td>
                            <td><input asp-for="AddNumber"/></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2"><label>Email Addresses</label></th>
                            <th><label>Delete?</label></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Client.EmailAddresses != null && Model.Client.EmailAddresses.Any())
                        {
                            int emailIndex = 1;

                            @foreach (var email in Model.Client.EmailAddresses)
                            {
                                <tr>
                                    <td>@emailIndex</td>
                                    <td><label>@email.Email</label></td>
                                    <td><input type="checkbox" name="selectedEmails" value="@email.EmailAddressID" /></td>
                                </tr>
                                emailIndex++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="3">No email addresses available</td>
                            </tr>
                        }
                        <tr>
                            <td>New</td>
                            <td><input asp-for="AddEmail" /></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row p-3 ps-0">
            <div class="col-3 w-auto">
                <label asp-for="Client.ReferringClientID">Referring Client</label>
                <select asp-for="Client.ReferringClientID" asp-items="@Model.ReferrerSelectList">
                    <option value=""></option>
                </select>
            </div>
        </div>
        <div class="row p-3">
            <div class="col-3 w-auto">
                <a asp-page="Clients">Cancel</a>
            </div>
            <div class="col-3 w-auto">
                <input value="Update Client" type="submit" class="btn btn-primary" asp-page-handler="UpdateClient" />
            </div>
        </div>
    </form>
</div>

ClientMaster/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="p-3">ClientMaster</h1>
    <a asp-page="/Clients" class="btn btn-primary">View Clients</a>
</div>